# Generated by Django 5.2.16 on 2026-07-15 21:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_menuanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributorEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('message_uid', models.CharField(max_length=200, unique=True)),
                ('sender', models.CharField(blank=True, max_length=300)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('raw_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('analyzed', 'Analyzed'), ('failed', 'Failed')], max_length=20)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('reviewed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-received_at', '-created'],
            },
        ),
    ]
