# Generated by Django 5.2.16 on 2026-07-16 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0004_tasteprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuanalysis',
            name='occasion',
        ),
        migrations.AddField(
            model_name='menuanalysis',
            name='food',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='menuanalysis',
            name='notes',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='tasteprofile',
            name='menu_best_value',
            field=models.BooleanField(default=True, verbose_name='Best value (quality-for-price, ranked across price tiers)'),
        ),
        migrations.AddField(
            model_name='tasteprofile',
            name='menu_most_interesting',
            field=models.BooleanField(default=True, verbose_name='Most interesting (rare grapes, unusual regions)'),
        ),
        migrations.AddField(
            model_name='tasteprofile',
            name='menu_notes',
            field=models.TextField(blank=True, help_text="Always applied to restaurant lists, e.g. 'I usually want the cost-effective option unless it's a special occasion' or 'bottles only, never glasses'.", verbose_name='Standing menu instructions'),
        ),
        migrations.AddField(
            model_name='tasteprofile',
            name='menu_taste_match',
            field=models.BooleanField(default=True, verbose_name='Your taste match (bottles most like what you love)'),
        ),
    ]
