# Generated by Django 5.2.16 on 2026-07-16 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0005_remove_menuanalysis_occasion_menuanalysis_food_and_more'),
        ('cellar', '0003_vintage_dossier_error_vintage_dossier_requested_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labelscan',
            name='vintage',
            field=models.ForeignKey(blank=True, help_text='The vintage this scan became once confirmed through intake', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='label_scans', to='cellar.vintage'),
        ),
    ]
