# Generated by Django 5.2.16 on 2026-07-16 15:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0006_labelscan_vintage'),
        ('cellar', '0006_wine_style_caption_wine_style_vector'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('producer_name', models.CharField(max_length=200)),
                ('wine_name', models.CharField(max_length=200)),
                ('wine_type', models.CharField(blank=True, max_length=20)),
                ('varietals', models.CharField(blank=True, max_length=200)),
                ('region', models.CharField(blank=True, max_length=200)),
                ('why', models.TextField(blank=True, help_text="The AI's reasoning, or scan context")),
                ('source', models.CharField(choices=[('research', 'Came up in research'), ('requested', 'Asked the sommelier'), ('scanned', "Scanned, didn't buy")], max_length=20)),
                ('status', models.CharField(choices=[('watching', 'Watching'), ('promoted', 'Promoted'), ('dismissed', 'Dismissed')], default='watching', max_length=20)),
                ('style_vector', models.JSONField(blank=True, help_text='Optional taste fingerprint (map dashed dot)', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospects', to=settings.AUTH_USER_MODEL)),
                ('label_scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospects', to='assistant.labelscan')),
                ('promoted_wine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospects', to='cellar.wine')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
