# Generated by Django 5.2.16 on 2026-07-16 16:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0007_prospect'),
        ('cellar', '0006_wine_style_caption_wine_style_vector'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValuationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Valuing…'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('general_note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valuation_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='VintageValuation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('per_bottle_value', models.DecimalField(blank=True, decimal_places=2, help_text="Estimated USD for a 750 ml bottle; null = couldn't price", max_digits=8, null=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='assistant.valuationrun')),
                ('vintage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='cellar.vintage')),
            ],
            options={
                'ordering': ['-created'],
                'constraints': [models.UniqueConstraint(fields=('run', 'vintage'), name='one_value_per_run_vintage')],
            },
        ),
    ]
