# Generated by Django 5.2.16 on 2026-07-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0008_valuationrun_vintagevaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasteprofile',
            name='distributor_best_value',
            field=models.BooleanField(default=True, verbose_name='Distributor: best value (quality-for-price, market flags)'),
        ),
        migrations.AddField(
            model_name='tasteprofile',
            name='distributor_most_interesting',
            field=models.BooleanField(default=True, verbose_name='Distributor: most interesting (rare/unusual, worth grabbing)'),
        ),
        migrations.AddField(
            model_name='tasteprofile',
            name='distributor_notes',
            field=models.TextField(blank=True, help_text="Always applied to distributor offers, e.g. 'flag anything I already own', 'I collect Loire whites', 'skip anything over $80/btl'.", verbose_name='Standing buying instructions'),
        ),
        migrations.AddField(
            model_name='tasteprofile',
            name='distributor_taste_match',
            field=models.BooleanField(default=True, verbose_name='Distributor: taste match (offers most like what you love)'),
        ),
        migrations.AlterField(
            model_name='distributoremail',
            name='status',
            field=models.CharField(choices=[('analyzed', 'Analyzed'), ('forwarded', 'Forwarded (not a wine offer)'), ('failed', 'Failed')], max_length=20),
        ),
    ]
