# Generated by Django 5.2.16 on 2026-07-15 21:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bottle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('size', models.CharField(choices=[('375ml', '375 ml (half)'), ('750ml', '750 ml'), ('1l', '1 L'), ('1.5l', '1.5 L (magnum)'), ('3l', '3 L (double magnum)')], default='750ml', max_length=10)),
                ('status', models.CharField(choices=[('in_cellar', 'In cellar'), ('consumed', 'Consumed'), ('gifted', 'Gifted')], default='in_cellar', max_length=20)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('purchase_source', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, help_text="Free text, e.g. 'rack B, row 3'", max_length=200)),
                ('consumed_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('region', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vintage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField(blank=True, help_text='Blank for non-vintage (NV)', null=True)),
                ('abv', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('drink_from', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('drink_until', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('window_rationale', models.TextField(blank=True, help_text='Why this window — AI suggestion rationale or your own note')),
            ],
            options={
                'ordering': ['wine__producer__name', 'wine__name', 'year'],
            },
        ),
        migrations.CreateModel(
            name='TastingNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('tasted_date', models.DateField(default=django.utils.timezone.localdate)),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='50–100 point scale', null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(100)])),
                ('notes', models.TextField(blank=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasting_notes', to=settings.AUTH_USER_MODEL)),
                ('bottle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasting_notes', to='cellar.bottle')),
                ('vintage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasting_notes', to='cellar.vintage')),
            ],
            options={
                'ordering': ['-tasted_date', '-created'],
            },
        ),
        migrations.AddField(
            model_name='bottle',
            name='vintage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bottles', to='cellar.vintage'),
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('wine_type', models.CharField(choices=[('red', 'Red'), ('white', 'White'), ('rose', 'Rosé'), ('sparkling', 'Sparkling'), ('dessert', 'Dessert'), ('fortified', 'Fortified')], max_length=20)),
                ('varietals', models.CharField(blank=True, help_text="Comma-separated, e.g. 'Cabernet Sauvignon, Merlot'", max_length=200)),
                ('appellation', models.CharField(blank=True, max_length=200)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wines', to='cellar.producer')),
            ],
            options={
                'ordering': ['producer__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='vintage',
            name='wine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vintages', to='cellar.wine'),
        ),
        migrations.AddConstraint(
            model_name='wine',
            constraint=models.UniqueConstraint(fields=('producer', 'name'), name='unique_wine_per_producer'),
        ),
        migrations.AddConstraint(
            model_name='vintage',
            constraint=models.UniqueConstraint(fields=('wine', 'year'), name='unique_year_per_wine'),
        ),
    ]
