# Generated by Django 5.2.16 on 2026-07-16 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vintage',
            name='dossier',
            field=models.JSONField(blank=True, help_text='AI web-research background (assistant.schemas.WineDossier shape)', null=True),
        ),
    ]
