# Generated by Django 5.2.16 on 2026-07-16 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0002_vintage_dossier'),
    ]

    operations = [
        migrations.AddField(
            model_name='vintage',
            name='dossier_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vintage',
            name='dossier_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vintage',
            name='dossier_status',
            field=models.CharField(blank=True, choices=[('pending', 'Researching'), ('failed', 'Failed')], default='', help_text='Blank when idle; research runs in a background thread', max_length=20),
        ),
        migrations.AddField(
            model_name='vintage',
            name='wishlist',
            field=models.BooleanField(default=False, help_text='Want to buy — tracked without any bottles in the cellar'),
        ),
    ]
