# Generated by Django 5.2.16 on 2026-07-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0003_vintage_dossier_error_vintage_dossier_requested_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle',
            name='opened_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='status',
            field=models.CharField(choices=[('in_cellar', 'In cellar'), ('open', 'Open'), ('consumed', 'Consumed'), ('gifted', 'Gifted')], default='in_cellar', max_length=20),
        ),
    ]
