# Generated by Django 5.2.16 on 2026-07-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0004_bottle_opened_date_alter_bottle_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='keeps_open_days',
            field=models.PositiveSmallIntegerField(blank=True, help_text='How many days an opened bottle stays good — AI-suggested by research, yours to override. Blank = the app has no opinion.', null=True),
        ),
    ]
