# Generated by Django 5.2.16 on 2026-07-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0005_wine_keeps_open_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='style_caption',
            field=models.CharField(blank=True, help_text='One-line style summary from the fingerprint', max_length=200),
        ),
        migrations.AddField(
            model_name='wine',
            name='style_vector',
            field=models.JSONField(blank=True, help_text='AI taste fingerprint (assistant.schemas.StyleVector shape) — powers the taste map. Regenerate via assistant_backfill_styles --refresh.', null=True),
        ),
    ]
