# Generated by Django 5.2.16 on 2026-07-30 13:31

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0006_wine_style_caption_wine_style_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='tastingnote',
            name='rating_5',
            field=models.DecimalField(blank=True, choices=[(Decimal('1.0'), '1 — never again'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2 — not good, not offensive'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), "3 — okay, don't seek out or avoid"), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4 — good, I like this'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5 — amazing')], decimal_places=1, help_text='Personal 5-point scale, half steps', max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='vintage',
            name='critic_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Official/critic score on the 50–100 scale, if research turned one up. Distinct from our own tasting-note ratings, which use the 5-point scale.', null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='vintage',
            name='critic_source',
            field=models.CharField(blank=True, help_text='Who scored it, e.g. "Wine Spectator 2022"', max_length=100),
        ),
    ]
