# Generated by Django 5.2.16 on 2026-07-30 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0008_migrate_ratings_to_five_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tastingnote',
            name='rating',
        ),
    ]
