# Generated by Django 5.2.16 on 2026-07-30 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0009_drop_legacy_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tastingnote',
            old_name='rating_5',
            new_name='rating',
        ),
    ]
